### ISSUE TITLE
Refactor orientation management in pyFAI-calib2 widget

### ISSUE THREAD

**Issue by kif** [silx-kit/pyFAI#2027]
Follow up of #2020

You should create a dedicated class for the orientation.
You can feel like it is overkill, but that's the way not to be over bloated with implementation details after years.

*    set/get will deal with your enum values, you don't have to think about
*    you can put your component inside detector-selection-drop.ui directly

**Comment by kif** [comment]
Some related issues:
* [ ] #2174: make some nice sketches to explain the difference
* [ ] #2176: offer the option to flip horizontally an image in a silx image
* [ ] #2177: new a marker for the detector origin
* [ ] #2175: update the code in `calib2`
